// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: addApikey.sql

package database

import (
	"context"
	"database/sql"
)

const addApikey = `-- name: AddApikey :one
UPDATE users SET api_key = $1 WHERE username = $2
RETURNING id, username, api_key
`

type AddApikeyParams struct {
	ApiKey   sql.NullString
	Username string
}

type AddApikeyRow struct {
	ID       int32
	Username string
	ApiKey   sql.NullString
}

func (q *Queries) AddApikey(ctx context.Context, arg AddApikeyParams) (AddApikeyRow, error) {
	row := q.db.QueryRowContext(ctx, addApikey, arg.ApiKey, arg.Username)
	var i AddApikeyRow
	err := row.Scan(&i.ID, &i.Username, &i.ApiKey)
	return i, err
}
