// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: loginUser.sql

package database

import (
	"context"
)

const loginUser = `-- name: LoginUser :one
SELECT id, username, password, role, status, created_at, updated_at, api_key from users
WHERE username = $1 AND password = $2
`

type LoginUserParams struct {
	Username string
	Password string
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKey,
	)
	return i, err
}
