// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: loginUser.sql

package database

import (
	"context"
)

const selectUser = `-- name: SelectUser :one
SELECT id, username, password, role, status, created_at, updated_at from users
WHERE username = $1
`

func (q *Queries) SelectUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
